shellEmulator: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080

trustPolicyExclude:
  - '@flatten-js/core@1.6.12'

packages:
  - apps/**
  - packages/**

patchedDependencies:
  '@ts-rest/core': patches/@ts-rest__core.patch

onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - sharp
  - simple-git-hooks
