shellEmulator: true

trustPolicy: no-downgrade

packages:
  - apps/**
  - packages/**

patchedDependencies:
  '@ts-rest/core': patches/@ts-rest__core.patch

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - es5-ext
  - esbuild
  - json-editor-vue
  - msgpackr-extract
  - puppeteer
  - sharp
  - simple-git-hooks
  - vue-demi
