shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - axios@1.13.3
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - apps/**
  - packages/**

patchedDependencies:
  '@ts-rest/core': patches/@ts-rest__core.patch

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - es5-ext
  - esbuild
  - json-editor-vue
  - msgpackr-extract
  - puppeteer
  - sharp
  - simple-git-hooks
  - vue-demi
