shellEmulator: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
trustPolicyExclude:
  - xlsx@0.20.3

pmOnFail: warn

packages:
  - apps/**
  - packages/**

overrides:
  axios: ^1.16.1

patchedDependencies:
  '@ts-rest/core': patches/@ts-rest__core.patch
  sharp@0.33.5: patches/sharp@0.33.5.patch
  sharp@0.34.5: patches/sharp@0.34.5.patch

allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: true
  json-editor-vue: false
  msgpackr-extract: false
  puppeteer: true
  sharp: true
  simple-git-hooks: true
  vue-demi: false
