export const XLSX_SHEET_NAMES = {
  altNames: 'Alt. names',
  asServedImages: 'As served images',
  asServedSets: 'As served sets',
  associatedFoods: 'Associated foods',
  attributes: 'Attributes',
  brands: 'Brands',
  categoriesMasterList: 'Categories master list',
  categoryStructure: 'Category structure',
  drinkwareScales: 'Drinkware scales',
  drinkwareSets: 'Drinkware sets',
  foodsMasterList: 'Foods master list',
  guideImageObjects: 'Guide image objects',
  guideImages: 'Guide images',
  imageMapObjects: 'Image map objects',
  imageMaps: 'Image maps',
  locales: 'Locales',
  nutrientMapping: 'Nutrient mapping',
  parentFoodPortion: 'Parent food portion',
  portionSize: 'Portion size',
  standardUnits: 'Standard units',
  synonymSets: 'Synonym sets',
  tags: 'Tags',
} as const;

export const XLSX_COLUMN_NAMES = {
  altNames: {
    alternativeName: 'Alternative Name',
    code: 'Code',
    language: 'Language',
  },
  associatedFoods: {
    associatedCategoryCode: 'Associated category code',
    associatedFoodCode: 'Associated food code',
    code: 'Code',
    genericName: 'Generic name',
    language: 'Language',
    linkAsMain: 'Link as main',
    multiple: 'Multiple',
    promptText: 'Prompt text',
  },
  attributes: {
    readyMealOption: 'Ready Meal Option',
    reasonableAmount: 'Reasonable Amount',
    sameAsBeforeOption: 'Same As Before Option',
    useInRecipes: 'Use In Recipes',
  },
  categoriesMasterList: {
    code: 'Code',
    englishName: 'English name',
    hidden: 'Hidden',
    name: 'Name',
    parentCategories: 'Parent categories',
  },
  categoryStructure: {
    code: 'Code',
    englishName: 'English name',
    hidden: 'Hidden',
    localName: 'Local name',
  },
  common: {
    code: 'Code',
    description: 'Description',
    id: 'ID',
    labelJson: 'Label JSON',
  },
  foodsMasterList: {
    action: 'Action',
    code: 'Code',
    englishName: 'English Name',
    name: 'Name',
    parentCategories: 'Parent Categories',
    thumbnailPath: 'Thumbnail Path',
  },
  brands: {
    brandName: 'Brand Name',
    code: 'Code',
  },
  locales: {
    adminLanguage: 'Admin Language',
    englishName: 'English Name',
    flagCode: 'Flag Code',
    foodIndexLanguageBackendId: 'Food Index Language Backend ID',
    id: 'ID',
    localName: 'Local Name',
    respondentLanguage: 'Respondent Language',
    textDirection: 'Text Direction',
  },
  nutrientMapping: {
    code: 'Code',
    nutrientRecordId: 'Nutrient Record Id',
    nutrientTableId: 'Nutrient Table Id',
  },
  parentFoodPortion: {
    category: 'Category',
    conversionFactor: 'Conversion factor',
    label: 'Label',
    language: 'Language',
    methodType: 'Method type',
    parentPortion: 'Parent portion',
    portionSizeOption: 'Portion size option',
    shortLabel: 'Short label',
  },
  portionSize: {
    asServed: 'As served',
    asServedConversionFactor: 'Conversion factor',
    asServedLeftoversImageSetId: 'Leftovers image set ID',
    asServedMultipleOption: 'Multiple option',
    asServedPathways: 'Pathways',
    asServedServingImageSetId: 'Serving image set ID',
    asServedShowLabels: 'Show labels',
    auto: 'Auto',
    autoConversionFactor: 'Conversion factor',
    autoMode: 'Mode',
    autoPathways: 'Pathways',
    autoValue: 'Value',
    categoryCode: 'Category code',
    categoryName: 'Category name',
    cereals: 'Cereals',
    cerealConversionFactor: 'Conversion factor',
    cerealPathways: 'Pathways',
    cerealShowLabels: 'Show labels',
    cerealType: 'Cereal type',
    colorGroup: 'Color group',
    dontKnowOption: '"Don\'t know" option',
    drinkScale: 'Drink scale',
    drinkScaleConversionFactor: 'Conversion factor',
    drinkScaleDrinkwareSetId: 'Drinkware set ID',
    drinkScaleInitialFillLevel: 'Initial fill level',
    drinkScaleMultipleOption: 'Multiple option',
    drinkScalePathways: 'Pathways',
    drinkScaleShowLabels: 'Show labels',
    drinkScaleSkipFillLevel: 'Skip fill level',
    enterWeightOption: '"Enter weight" option',
    foodCode: 'Food code',
    foodName: 'Food name',
    guideImage: 'Guide image',
    guideImageConversionFactor: 'Conversion factor',
    guideImageId: 'Guide image ID',
    guideImageShowLabels: 'Show labels',
    guideImageVisibility: 'Visibility',
    milkOnCereal: 'Milk on cereal',
    milkOnCerealConversionFactor: 'Conversion factor',
    milkOnCerealPathways: 'Pathways',
    milkOnCerealShowLabels: 'Show labels',
    pizza: 'Pizza',
    pizzaConversionFactor: 'Conversion factor',
    pizzaPathways: 'Pathways',
    pizzaShowLabels: 'Show labels',
    pizzaV2: 'Pizza (Version 2)',
    pizzaV2ConversionFactor: 'Conversion factor',
    pizzaV2Pathways: 'Pathways',
    pizzaV2ShowLabels: 'Show labels',
  },
  portionSizeReference: {
    baseImagePath: 'Base Image Path',
    choiceId: 'Choice ID',
    emptyLevel: 'Empty Level',
    fullLevel: 'Full Level',
    guideImageId: 'Guide Image ID',
    height: 'Height',
    imageMapId: 'Image Map ID',
    imageMapObjectId: 'Object ID',
    imagePath: 'Image Path',
    keywords: 'Keywords',
    navigationIndex: 'Navigation Index',
    outlineCoordinates: 'Outline Coordinates',
    overlayImagePath: 'Overlay Image Path',
    selectionImagePath: 'Selection Image Path',
    selectionImageMapId: 'Selection Image Map ID',
    setId: 'Set ID',
    version: 'Version',
    volumeMethod: 'Volume Method',
    volumeSamples: 'Volume Samples',
    weight: 'Weight',
    width: 'Width',
  },
  tags: {
    code: 'Code',
    tag: (index: number) => `Tag ${index}`,
  },
  standardUnits: {
    conversionFactor: 'Conversion factor',
    inlineEstimateIn: 'Inline estimate in',
    inlineHowMany: 'Inline how many',
    omitFoodName: 'Omit food name',
    portionSizeOption: 'Portion size option',
    standardUnitId: 'Standard unit ID',
    unitWeight: 'Unit weight',
  },
  synonymSets: {
    locale: 'Locale',
    synonyms: 'Synonyms',
  },
} as const;
