import { defineConfig } from 'kysely-codegen';

export default defineConfig({
  camelCase: true,
  dialect: 'postgres',
  url: 'env(DB_DEV_SYSTEM_URL)',
  envFile: '../../apps/api/.env',
  outFile: './src/kysely/system.d.ts',
  customImports: {
    // Survey related types
    SurveyState: '@intake24/common/surveys#SurveyState',
    // FAQ related types
    FAQSection: '@intake24/common/types/http/admin#FAQSection',
    // Feedback related types
    Card: '@intake24/common/feedback#Card',
    DemographicGroup: '@intake24/common/feedback#DemographicGroup',
    FeedbackMeals: '@intake24/common/feedback#FeedbackMeals',
    FeedbackOutput: '@intake24/common/feedback#FeedbackOutput',
    FeedbackPhysicalDataField: '@intake24/common/feedback#FeedbackPhysicalDataField',
    FeedbackSection: '@intake24/common/feedback#FeedbackSection',
    FeedbackType: '@intake24/common/feedback#FeedbackType',
    HenryCoefficient: '@intake24/common/feedback#HenryCoefficient',
    TopFoods: '@intake24/common/feedback#TopFoods',
    // Job related types
    JobType: '@intake24/common/types#JobType',
    JobTypeParams: '@intake24/common/types#JobTypeParams',
    // i18n related types
    LocaleMessageDictionary: '@intake24/i18n#LocaleMessageDictionary',
    // MFA related types
    AuthenticatorTransportFuture: '@simplewebauthn/server#AuthenticatorTransportFuture',
    CredentialDeviceType: '@simplewebauthn/server#CredentialDeviceType',
    // Survey related types
    SchemeOverrides: '@intake24/common/surveys#SchemeOverrides',
    SessionSettings: '@intake24/common/surveys#SessionSettings',
    SurveyAuthMode: '@intake24/common/surveys#SurveyAuthMode',
    SurveySearchSettings: '@intake24/common/surveys#SurveySearchSettings',
    SurveyStatus: '@intake24/common/surveys#SurveyStatus',
    Notification: '@intake24/common/types#Notification',
    // SurveySchemePrompt related types
    SinglePrompt: '@intake24/common/prompts#SinglePrompt',
    // SurveyScheme related types
    ExportSection: '@intake24/common/surveys#ExportSection',
    Meal: '@intake24/common/surveys#Meal',
    RecallPrompts: '@intake24/common/surveys#RecallPrompts',
    SchemeSettings: '@intake24/common/surveys#SchemeSettings',
    // Submission related types
    CustomData: '@intake24/common/surveys#CustomData',
    PortionSizeMethodId: '@intake24/common/surveys#PortionSizeMethodId',
    PortionSizeState: '@intake24/common/surveys#PortionSizeState',
    Dictionary: '@intake24/common/types#Dictionary',
    // Security related types
    SecurableType: '@intake24/common/security#SecurableType',
    RecordVisibility: '@intake24/common/security#RecordVisibility',
    MFAProvider: '@intake24/common/security#MFAProvider',
    // User subscription related types
    Subscription: '@intake24/common/types#Subscription',
    SubscriptionType: '@intake24/common/types#SubscriptionType',
  },
  overrides: {
    columns: {
      'client_error_reports.survey_state_json': 'SurveyState',
      'faqs.content': 'FAQSection[]',
      'faqs.visibility': 'Generated<RecordVisibility>',
      'feedback_schemes.cards': 'Generated<Card[]>',
      'feedback_schemes.demographic_groups': 'Generated<DemographicGroup[]>',
      'feedback_schemes.meals': 'FeedbackMeals',
      'feedback_schemes.outputs': 'Generated<FeedbackOutput[]>',
      'feedback_schemes.physical_data_fields': 'Generated<FeedbackPhysicalDataField[]>',
      'feedback_schemes.sections': 'Generated<FeedbackSection[]>',
      'feedback_schemes.type': 'FeedbackType',
      'feedback_schemes.henry_coefficients': 'Generated<HenryCoefficient[]>',
      'feedback_schemes.top_foods': 'TopFoods',
      'feedback_schemes.visibility': 'Generated<RecordVisibility>',
      'jobs.type': 'JobType',
      'jobs.params': 'JobTypeParams',
      'languages.visibility': 'Generated<RecordVisibility>',
      'language_translations.messages': 'LocaleMessageDictionary<any>',
      'locales.visibility': 'Generated<RecordVisibility>',
      'mfa_devices.provider': 'MFAProvider',
      'mfa_authenticators.public_key': 'Uint8Array<ArrayBuffer>',
      'mfa_authenticators.device_type': 'CredentialDeviceType',
      'mfa_authenticators.transports': 'AuthenticatorTransportFuture[]',
      'personal_access_tokens.scopes': 'string[] | null',
      'surveys.auth_modes': 'Generated<SurveyAuthMode[]>',
      'surveys.notifications': 'Generated<Notification[]>',
      'surveys.survey_scheme_overrides': 'SchemeOverrides',
      'surveys.session': 'SessionSettings',
      'surveys.search_settings': 'SurveySearchSettings',
      'surveys.state': 'SurveyStatus',
      'survey_scheme_prompts.prompt': 'SinglePrompt',
      'survey_schemes.data_export': 'Generated<ExportSection[]>',
      'survey_schemes.meals': 'Generated<Meal[]>',
      'survey_schemes.prompts': 'RecallPrompts',
      'survey_schemes.settings': 'SchemeSettings',
      'survey_schemes.visibility': 'Generated<RecordVisibility>',
      'survey_submission_foods.custom_data': 'CustomData | null',
      'survey_submission_foods.fields': 'Dictionary<string> | null',
      'survey_submission_foods.nutrients': 'Dictionary<number> | null',
      'survey_submission_foods.portion_size': 'PortionSizeState | null',
      'survey_submission_foods.portion_size_method_id': 'PortionSizeMethodId',
      'survey_submission_meals.custom_data': 'CustomData | null',
      'survey_submissions.custom_data': 'CustomData | null',
      'tasks.params': 'JobTypeParams',
      'user_securables.fields': 'string[] | null',
      'user_securables.securable_type': 'SecurableType',
      'user_subscriptions.subscription': 'Subscription',
      'user_subscriptions.type': 'SubscriptionType',
      'user_survey_sessions.session_data': 'SurveyState',
    },
  },
});
