/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { AuthenticatorTransportFuture, CredentialDeviceType } from '@simplewebauthn/server';
import type { ColumnType } from 'kysely';

import type { Card, DemographicGroup, FeedbackMeals, FeedbackOutput, FeedbackPhysicalDataField, FeedbackSection, FeedbackType, HenryCoefficient, TopFoods } from '@intake24/common/feedback';
import type { SinglePrompt } from '@intake24/common/prompts';
import type { MFAProvider, RecordVisibility, SecurableType } from '@intake24/common/security';
import type { CustomData, ExportSection, Meal, PortionSizeMethodId, PortionSizeState, RecallPrompts, SchemeOverrides, SchemeSettings, SessionSettings, SurveyAuthMode, SurveySearchSettings, SurveyState, SurveyStatus } from '@intake24/common/surveys';
import type { Dictionary, JobType, JobTypeParams, Notification, Subscription, SubscriptionType } from '@intake24/common/types';
import type { FAQSection } from '@intake24/common/types/http/admin';
import type { LocaleMessageDictionary } from '@intake24/i18n';

export type EnumMediaDisk = 'private' | 'public';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ClientErrorReports {
  createdAt: Timestamp;
  id: Generated<Int8>;
  new: Generated<boolean>;
  stackTrace: string;
  surveyId: Int8 | null;
  surveyStateJson: SurveyState;
  updatedAt: Timestamp;
  userId: Int8 | null;
}

export interface ExternalTestUsers {
  confirmationCode: string;
  externalUserId: string;
  id: Generated<number>;
  userId: Int8;
}

export interface Faqs {
  content: FAQSection[];
  createdAt: Timestamp;
  id: Generated<Int8>;
  name: string;
  ownerId: Int8 | null;
  updatedAt: Timestamp;
  visibility: Generated<RecordVisibility>;
}

export interface FeedbackSchemes {
  cards: Generated<Card[]>;
  createdAt: Timestamp;
  demographicGroups: Generated<DemographicGroup[]>;
  henryCoefficients: Generated<HenryCoefficient[]>;
  id: Generated<Int8>;
  meals: FeedbackMeals;
  name: string;
  outputs: Generated<FeedbackOutput[]>;
  ownerId: Int8 | null;
  physicalDataFields: Generated<FeedbackPhysicalDataField[]>;
  sections: Generated<FeedbackSection[]>;
  topFoods: TopFoods;
  type: FeedbackType;
  updatedAt: Timestamp;
  visibility: Generated<RecordVisibility>;
}

export interface FixedFoodRanking {
  foodCode: string;
  id: Generated<number>;
  localeId: string;
  rank: number;
}

export interface GenUserCounters {
  count: number;
  createdAt: Timestamp;
  surveyId: Int8;
  updatedAt: Timestamp;
}

export interface Jobs {
  completedAt: Timestamp | null;
  createdAt: Timestamp;
  downloadUrl: string | null;
  downloadUrlExpiresAt: Timestamp | null;
  errorDetails: Json | null;
  id: Generated<Int8>;
  message: string | null;
  params: JobTypeParams;
  progress: number | null;
  returnValue: Json | null;
  stackTrace: string | null;
  startedAt: Timestamp | null;
  successful: boolean | null;
  type: JobType;
  updatedAt: Timestamp;
  userId: Int8 | null;
}

export interface Languages {
  code: string;
  countryFlagCode: string;
  createdAt: Timestamp;
  englishName: string;
  id: Generated<Int8>;
  localName: string;
  ownerId: Int8 | null;
  textDirection: Generated<string>;
  updatedAt: Timestamp;
  visibility: Generated<RecordVisibility>;
}

export interface LanguageTranslations {
  application: string;
  createdAt: Timestamp;
  id: Generated<Int8>;
  languageId: Int8 | null;
  messages: LocaleMessageDictionary<any>;
  section: string;
  updatedAt: Timestamp;
}

export interface Locales {
  adminLanguageId: string;
  code: string;
  countryFlagCode: string;
  createdAt: Timestamp;
  englishName: string;
  foodIndexEnabled: Generated<boolean>;
  foodIndexLanguageBackendId: Generated<string>;
  id: Generated<Int8>;
  localName: string;
  ownerId: Int8 | null;
  respondentLanguageId: string;
  textDirection: Generated<string>;
  updatedAt: Timestamp;
  visibility: Generated<RecordVisibility>;
}

export interface Media {
  collection: string;
  createdAt: Timestamp;
  disk: EnumMediaDisk;
  filename: string;
  id: string;
  mimetype: string;
  modelId: string | null;
  modelType: string;
  name: string;
  size: number;
  updatedAt: Timestamp;
}

export interface MfaAuthenticators {
  backedUp: boolean;
  counter: Int8;
  createdAt: Timestamp;
  deviceId: Int8;
  deviceType: CredentialDeviceType;
  id: string;
  publicKey: Uint8Array<ArrayBuffer>;
  transports: AuthenticatorTransportFuture[];
  updatedAt: Timestamp;
}

export interface MfaDevices {
  createdAt: Timestamp;
  id: Generated<Int8>;
  name: string;
  preferred: Generated<boolean>;
  provider: MFAProvider;
  secret: string;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface MissingFoods {
  brand: string;
  description: string;
  id: Generated<Int8>;
  leftovers: string;
  name: string;
  portionSize: string;
  submittedAt: Timestamp;
  surveyId: Int8;
  userId: Int8;
}

export interface NutrientTypes {
  description: string;
  id: Int8;
  unitId: Int8;
}

export interface NutrientUnits {
  description: string;
  id: Int8;
  symbol: string;
}

export interface PairwiseAssociationsCoOccurrences {
  antecedentFoodCode: string;
  consequentFoodCode: string;
  localeId: string;
  occurrences: number;
}

export interface PairwiseAssociationsOccurrences {
  foodCode: string;
  localeId: string;
  multiplier: number | null;
  occurrences: number;
}

export interface PairwiseAssociationsTransactionsCount {
  localeId: string;
  transactionsCount: number;
}

export interface PermissionRole {
  createdAt: Timestamp;
  permissionId: Int8;
  roleId: Int8;
  updatedAt: Timestamp;
}

export interface Permissions {
  createdAt: Timestamp;
  description: string | null;
  displayName: string;
  id: Generated<Int8>;
  name: string;
  updatedAt: Timestamp;
}

export interface PermissionUser {
  createdAt: Timestamp;
  permissionId: Int8;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface PersonalAccessTokens {
  createdAt: Timestamp;
  expiresAt: Timestamp | null;
  id: Generated<Int8>;
  name: string;
  revoked: Generated<boolean>;
  scopes: string[] | null;
  token: string;
  updatedAt: Timestamp;
  usedAt: Timestamp | null;
  userId: Int8;
}

export interface PopularityCounters {
  counter: Generated<number>;
  foodCode: string;
}

export interface RefreshTokens {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  revoked: Generated<boolean>;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface Roles {
  createdAt: Timestamp;
  description: string | null;
  displayName: string;
  id: Generated<Int8>;
  name: string;
  updatedAt: Timestamp;
}

export interface RoleUser {
  createdAt: Timestamp;
  roleId: Int8;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface SequelizeMeta {
  name: string;
}

export interface ShortUrls {
  longUrl: string;
  shortUrl: string;
}

export interface SigninLog {
  date: Timestamp;
  id: Generated<Int8>;
  message: string | null;
  provider: string;
  providerKey: string;
  remoteAddress: string | null;
  successful: boolean;
  userAgent: string | null;
  userId: Int8 | null;
}

export interface Surveys {
  allowGenUsers: boolean | null;
  authCaptcha: Generated<boolean>;
  authModes: Generated<SurveyAuthMode[]>;
  authUrlDomainOverride: string | null;
  authUrlTokenCharset: string | null;
  authUrlTokenLength: number | null;
  createdAt: Timestamp;
  endDate: Timestamp;
  faqId: Int8 | null;
  feedbackSchemeId: Int8 | null;
  genUserKey: string | null;
  id: Generated<Int8>;
  localeId: Int8 | null;
  maximumDailySubmissions: Generated<number>;
  maximumTotalSubmissions: number | null;
  minimumSubmissionInterval: Generated<number>;
  name: string;
  notifications: Generated<Notification[]>;
  numberOfSubmissionsForFeedback: Generated<number>;
  originatingUrl: string | null;
  ownerId: Int8 | null;
  searchSettings: SurveySearchSettings;
  session: SessionSettings;
  slug: string;
  startDate: Timestamp;
  state: SurveyStatus;
  supportEmail: string | null;
  surveyMonkeyUrl: string | null;
  surveySchemeId: Int8;
  surveySchemeOverrides: SchemeOverrides;
  suspensionReason: string | null;
  updatedAt: Timestamp;
  userCustomFields: Generated<boolean>;
  userPersonalIdentifiers: Generated<boolean>;
}

export interface SurveySchemePrompts {
  createdAt: Timestamp;
  id: Generated<Int8>;
  name: string;
  prompt: SinglePrompt;
  promptId: string;
  updatedAt: Timestamp;
}

export interface SurveySchemes {
  createdAt: Timestamp;
  dataExport: Generated<ExportSection[]>;
  id: Generated<Int8>;
  meals: Generated<Meal[]>;
  name: string;
  ownerId: Int8 | null;
  prompts: RecallPrompts;
  settings: SchemeSettings;
  updatedAt: Timestamp;
  visibility: Generated<RecordVisibility>;
}

export interface SurveySubmissionExternalSources {
  data: Json | null;
  foodId: string;
  foodType: string;
  id: string;
  searchTerm: string | null;
  source: string;
  type: string | null;
}

export interface SurveySubmissionFoods {
  barcode: string | null;
  brand: string | null;
  code: string;
  customData: CustomData | null;
  englishName: string;
  fields: Dictionary<string> | null;
  id: string;
  index: number;
  locale: string;
  localName: string | null;
  mealId: string;
  nutrients: Dictionary<number> | null;
  nutrientTableCode: string;
  nutrientTableId: string;
  parentId: string | null;
  portionSize: PortionSizeState | null;
  portionSizeMethodId: PortionSizeMethodId;
  readyMeal: boolean;
  reasonableAmount: boolean;
  searchTerm: string;
}

export interface SurveySubmissionMeals {
  customData: CustomData | null;
  duration: number | null;
  hours: number;
  id: string;
  minutes: number;
  name: string | null;
  surveySubmissionId: string;
}

export interface SurveySubmissionMissingFoods {
  barcode: string | null;
  brand: string | null;
  description: string | null;
  id: string;
  index: number;
  leftovers: string | null;
  mealId: string;
  name: string | null;
  parentId: string | null;
  portionSize: string | null;
}

export interface SurveySubmissions {
  createdAt: Timestamp;
  customData: CustomData | null;
  endTime: Timestamp;
  id: string;
  log: string | null;
  recallDate: Timestamp | null;
  sessionId: string;
  sleepTime: string | null;
  startTime: Timestamp;
  submissionTime: Timestamp;
  surveyId: Int8;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: Int8;
  wakeUpTime: string | null;
}

export interface SurveysUxEventsSettings {
  createdAt: Timestamp;
  enableAssociatedFoodsEvents: boolean;
  enableSearchEvents: boolean;
  surveyId: Int8;
  updatedAt: Timestamp;
}

export interface Tasks {
  active: Generated<boolean>;
  createdAt: Timestamp;
  cron: string;
  description: string | null;
  id: Generated<Int8>;
  job: string;
  name: string;
  params: JobTypeParams;
  updatedAt: Timestamp;
}

export interface UserCustomFields {
  id: Generated<Int8>;
  name: string;
  public: Generated<boolean>;
  userId: Int8;
  value: string;
}

export interface UserNotificationSchedule {
  datetime: Timestamp;
  id: Generated<Int8>;
  notificationType: string | null;
  surveyId: Int8 | null;
  userId: Int8;
}

export interface UserPasswordResets {
  createdAt: Timestamp | null;
  id: Generated<Int8>;
  token: string;
  updatedAt: Timestamp | null;
  userId: Int8;
}

export interface UserPasswords {
  passwordHash: string;
  passwordHasher: string;
  passwordSalt: string;
  userId: Int8;
}

export interface UserPhysicalData {
  birthdate: Timestamp | null;
  heightCm: number | null;
  physicalActivityLevelId: Int8 | null;
  sex: string | null;
  userId: Int8;
  weightKg: number | null;
  weightTarget: string | null;
}

export interface Users {
  createdAt: Timestamp | null;
  disabledAt: Timestamp | null;
  email: string | null;
  emailNotifications: Generated<boolean>;
  id: Generated<Int8>;
  multiFactorAuthentication: Generated<boolean>;
  name: string | null;
  phone: string | null;
  simpleName: string | null;
  smsNotifications: Generated<boolean>;
  updatedAt: Timestamp | null;
  verifiedAt: Timestamp | null;
}

export interface UserSecurables {
  action: string;
  createdAt: Timestamp;
  fields: string[] | null;
  securableId: Int8;
  securableType: SecurableType;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface UserSubscriptions {
  createdAt: Timestamp;
  id: Generated<Int8>;
  subscription: Subscription;
  type: SubscriptionType;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface UserSurveyAliases {
  createdAt: Timestamp;
  id: Generated<Int8>;
  surveyId: Int8;
  updatedAt: Timestamp;
  urlAuthToken: string;
  userId: Int8;
  username: string;
}

export interface UserSurveyRatings {
  comment: string | null;
  createdAt: Timestamp;
  id: Generated<Int8>;
  rating: number;
  submissionId: string | null;
  surveyId: Int8;
  type: string;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface UserSurveySessions {
  createdAt: Timestamp;
  id: string;
  sessionData: SurveyState;
  surveyId: Int8;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface UxEvents {
  created: Generated<Timestamp>;
  data: Json;
  eventCategories: string[];
  eventType: string;
  id: Generated<number>;
  localTimestamp: Int8 | null;
  sessionId: string;
  userId: Int8;
}

export interface DB {
  clientErrorReports: ClientErrorReports;
  externalTestUsers: ExternalTestUsers;
  faqs: Faqs;
  feedbackSchemes: FeedbackSchemes;
  fixedFoodRanking: FixedFoodRanking;
  genUserCounters: GenUserCounters;
  jobs: Jobs;
  languages: Languages;
  languageTranslations: LanguageTranslations;
  locales: Locales;
  media: Media;
  mfaAuthenticators: MfaAuthenticators;
  mfaDevices: MfaDevices;
  missingFoods: MissingFoods;
  nutrientTypes: NutrientTypes;
  nutrientUnits: NutrientUnits;
  pairwiseAssociationsCoOccurrences: PairwiseAssociationsCoOccurrences;
  pairwiseAssociationsOccurrences: PairwiseAssociationsOccurrences;
  pairwiseAssociationsTransactionsCount: PairwiseAssociationsTransactionsCount;
  permissionRole: PermissionRole;
  permissions: Permissions;
  permissionUser: PermissionUser;
  personalAccessTokens: PersonalAccessTokens;
  popularityCounters: PopularityCounters;
  refreshTokens: RefreshTokens;
  roles: Roles;
  roleUser: RoleUser;
  sequelizeMeta: SequelizeMeta;
  shortUrls: ShortUrls;
  signinLog: SigninLog;
  surveys: Surveys;
  surveySchemePrompts: SurveySchemePrompts;
  surveySchemes: SurveySchemes;
  surveySubmissionExternalSources: SurveySubmissionExternalSources;
  surveySubmissionFoods: SurveySubmissionFoods;
  surveySubmissionMeals: SurveySubmissionMeals;
  surveySubmissionMissingFoods: SurveySubmissionMissingFoods;
  surveySubmissions: SurveySubmissions;
  surveysUxEventsSettings: SurveysUxEventsSettings;
  tasks: Tasks;
  userCustomFields: UserCustomFields;
  userNotificationSchedule: UserNotificationSchedule;
  userPasswordResets: UserPasswordResets;
  userPasswords: UserPasswords;
  userPhysicalData: UserPhysicalData;
  users: Users;
  userSecurables: UserSecurables;
  userSubscriptions: UserSubscriptions;
  userSurveyAliases: UserSurveyAliases;
  userSurveyRatings: UserSurveyRatings;
  userSurveySessions: UserSurveySessions;
  uxEvents: UxEvents;
}
